name: 📦 Build & Publish Rust Binaries

on:
  push:
    tags:
      - 'v*'  # triggers on tags like v0.4.1
      - '[0-9]*'   # catch numeric-only tags like 0.4.1

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo registry & Git data
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build (release)
        run: cargo build --locked --release --all-targets

      - name: Package binaries
        run: |
          mkdir -p dist
          case "${{ matrix.os }}" in
            ubuntu-latest)
              tar -czvf dist/cliptions-linux-v${{ github.ref_name }}.tar.gz -C target/release \
                cliptions_app \
                calculate_scores \
                generate_commitment \
                process_payouts \
                twitter_latest_tweet \
                twitter_post \
                twitter_search_replies \
                verify_commitments
              ;;
            macos-latest)
              tar -czvf dist/cliptions-macos-v${{ github.ref_name }}.tar.gz -C target/release \
                cliptions_app \
                calculate_scores \
                generate_commitment \
                process_payouts \
                twitter_latest_tweet \
                twitter_post \
                twitter_search_replies \
                verify_commitments
              ;;
            windows-latest)
              zip -j dist/cliptions-windows-v${{ github.ref_name }}.zip \
                target/release/cliptions_app.exe \
                target/release/calculate_scores.exe \
                target/release/generate_commitment.exe \
                target/release/process_payouts.exe \
                target/release/twitter_latest_tweet.exe \
                target/release/twitter_post.exe \
                target/release/twitter_search_replies.exe \
                target/release/verify_commitments.exe
              ;;
          esac

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Cliptions Core ${{ github.ref_name }}
            
            ### Binaries Included:
            - `cliptions_app` - Main application
            - `calculate_scores` - Score calculation utility
            - `generate_commitment` - Commitment generation
            - `process_payouts` - Payout processing
            - `twitter_latest_tweet` - Twitter utilities
            - `twitter_post` - Twitter posting
            - `twitter_search_replies` - Twitter reply search
            - `verify_commitments` - Commitment verification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
